kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "grafana.fullname" . }}-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  storageClassName: {{ .Values.storage.storageClass}}
  volumeMode: Filesystem
