nameOverride: ""
fullnameOverride: ""


deployment:
  replicaCount: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1

  image:
    repository: sonatype/nexus3
    pullPolicy: IfNotPresent
    tag: "3.71.0-ubi"

  livenessProbe:
    failureThreshold: 3
    httpGet:
      path: /
      port: 8081
      scheme: HTTP
    initialDelaySeconds: 60
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 120

  readinessProbe:
    failureThreshold: 3
    httpGet:
      path: /
      port: 8081
      scheme: HTTP
    initialDelaySeconds: 60
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 120

  port: 8081
  dockerPort: 8082

storage:
  size: 10Gi
  storageClass: proxmox-data-xfs

openshift:
  dominio: apps.ocp.dani.framos.nom.br


config: []