apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexus.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
spec:
  ports:
  - name: tcp-{{ .Values.deployment.port }}
    port: {{ .Values.deployment.port }}
    protocol: TCP
    targetPort: {{ .Values.deployment.port }}
  - name: tcp-{{ .Values.deployment.dockerPort }}
    port: {{ .Values.deployment.dockerPort }}
    protocol: TCP
    targetPort: {{ .Values.deployment.dockerPort }}
  selector:
    {{- include "nexus.selectorLabels" . | nindent 6 }}
  sessionAffinity: None
  type: ClusterIP