apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
spec:
  ports:
  - name: TCP
    port: {{ .Values.deployment.port }}
    protocol: TCP
    targetPort: {{ .Values.deployment.port }}
  selector:
    deployment: {{ include "prometheus.fullname" . }}
  sessionAffinity: None
  type: ClusterIP