nameOverride: ""
fullnameOverride: ""


deployment:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1

  image:
    repository: grafana/grafana
    pullPolicy: IfNotPresent
    tag: "11.1.1"
    pullPolicy: IfNotPresent

  livenessProbe:
    failureThreshold: 3
    httpGet:
      path: /
      port: 3000
      scheme: HTTP
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 120

  readinessProbe:
    failureThreshold: 3
    httpGet:
      path: /
      port: 3000
      scheme: HTTP
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 120

  port: 3000

storage:
  size: 10Gi
  storageClass: proxmox-data-xfs

openshift:
  dominio: apps.ocp.dani.framos.nom.br