apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "openshift-proxmox-csi-plugin.fullname" . }}-node
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openshift-proxmox-csi-plugin.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
