{{- if ne (len .Values.config.clusters) 0 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openshift-proxmox-csi-plugin.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openshift-proxmox-csi-plugin.labels" . | nindent 4 }}
type: Opaque
data:
  config.yaml: {{ toYaml .Values.config | b64enc | quote }}
{{- end }}
