{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openshift-proxmox-csi-plugin.serviceAccountName" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openshift-proxmox-csi-plugin.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openshift-proxmox-csi-plugin.serviceAccountName" . }}-node
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openshift-proxmox-csi-plugin.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
